# Generated by Django 4.2.2 on 2023-06-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=250)),
                ('image', models.URLField()),
                ('type', models.CharField(choices=[('1.Fantasy', 'Fantasy'), ('2.Roman', 'Roman'), ('3.Study', 'Study'), ('4.Modern', 'Modern'), ('5.Horror', 'Horror')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
