# Generated by Django 4.2.2 on 2023-06-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='type',
            field=models.CharField(choices=[('1.Fiction', 'Fiction'), ('2.Novel', 'Novel'), ('3.Crime', 'Crime'), ('4.Fantasy', 'Fantasy'), ('5.Roman', 'Roman'), ('6.Study', 'Study'), ('7.Modern', 'Modern'), ('8.Horror', 'Horror')], max_length=20),
        ),
    ]
